<template>
  <pre
    class="ascii-cat"
  ><b style="color:transparent">gg</b><b style="color:transparent">1</b><b style="color:#272839">a</b><b style="color:#444554">y</b><b style="color:#3F404F">1</b><b style="color:#303142">0</b><b style="color:#212133">u</b><b style="color:#121222">g</b><b style="color:transparent">y</b><b style="color:transparent">y</b><b style="color:transparent">g1g21u2gy1a000</b><b style="color:transparent">1</b><b style="color:transparent">u</b><b style="color:#1D1D2D">1</b><b style="color:#2F3040">1</b><b style="color:#3E404F">y</b><b style="color:#434453">2</b><b style="color:#2A2B3D">a</b><b style="color:#1F1F31">a</b>
<b style="color:transparent">ag</b><b style="color:#34354A">g</b><b style="color:#B5B2A9">y</b><b style="color:#EBDECA">y</b><b style="color:#E4D6C3">0</b><b style="color:#D6CDBC">g</b><b style="color:#BCBBAD">y</b><b style="color:#999A94">1</b><b style="color:#6F6F73">2</b><b style="color:#41414E">0</b><b style="color:#202031">1</b><b style="color:transparent">y</b><b style="color:transparent">0</b><b style="color:transparent">2</b><b style="color:transparent">2</b><b style="color:transparent">0</b><b style="color:transparent">a</b><b style="color:transparent">0</b><b style="color:transparent">g</b><b style="color:transparent">0</b><b style="color:transparent">a</b><b style="color:transparent">1</b><b style="color:#1C1C29">y</b><b style="color:#444451">g</b><b style="color:#77777C">1</b><b style="color:#A6A8A4">2</b><b style="color:#C4C3B7">y</b><b style="color:#D8CFBF">2</b><b style="color:#E5D5C3">y</b><b style="color:#EADDC9">2</b><b style="color:#B5B1A2">1</b><b style="color:#313241">0</b><b style="color:#2B2B41">1</b>
<b style="color:transparent">a</b><b style="color:#212237">1</b><b style="color:#806F77">a</b><b style="color:#FFD4C3">y</b><b style="color:#FFCBBC">1</b><b style="color:#FFC6B8">g</b><b style="color:#FDC6B8">a</b><b style="color:#FFD4C3">2</b><b style="color:#FFF3DD">u</b><b style="color:#FDFDEB">u</b><b style="color:#F3F3DC">a</b><b style="color:#C8C8B9">g</b><b style="color:#888887">2</b><b style="color:#606068">0</b><b style="color:#64646A">0</b><b style="color:#2F2F43">y</b><b style="color:#2C2C41">1</b><b style="color:#78787B">a</b><b style="color:#353549">g</b><b style="color:#29293F">u</b><b style="color:#5B5B62">1</b><b style="color:#5F5F65">1</b><b style="color:#949494">u</b><b style="color:#D2D2C5">y</b><b style="color:#F8F8E2">g</b><b style="color:#FFFFEB">g</b><b style="color:#FEEFD9">g</b><b style="color:#FED4C4">2</b><b style="color:#FCC5B7">2</b><b style="color:#FFC9BB">01</b><b style="color:#FFD5C5">a</b><b style="color:#826D69">g</b><b style="color:#25263D">y</b><b style="color:#212130">1</b>
<b style="color:transparent">0</b><b style="color:#27293F">0</b><b style="color:#C29996">g</b><b style="color:#FAC8B9">2</b><b style="color:#B18985">a</b><b style="color:#6C5D66">2</b><b style="color:#BCA29D">g</b><b style="color:#FFE0CE">a</b><b style="color:#FDF1DC">y</b><b style="color:#FFFFE7">a</b><b style="color:#FFFFE8">2</b><b style="color:#FFFFEC">0</b><b style="color:#FFFFED">a</b><b style="color:#FEFEE9">2</b><b style="color:#FFFFEE">0</b><b style="color:#90908F">0</b><b style="color:#4C4C59">u</b><b style="color:#EDEDD8">2</b><b style="color:#595964">u</b><b style="color:#727278">0</b><b style="color:#FEFEE8">2</b><b style="color:#FFFFEB">0</b><b style="color:#FFFFED">a</b><b style="color:#FFFFEB">g</b><b style="color:#FFFFE8">g</b><b style="color:#FEFEE6">y</b><b style="color:#FDEAD6">u</b><b style="color:#FEDAC8">a</b><b style="color:#9A857F">1</b><b style="color:#745F67">g</b><b style="color:#CFA19C">0</b><b style="color:#FFCEBF">2</b><b style="color:#C7998F">g</b><b style="color:#242537">y</b>
<b style="color:transparent">2</b><b style="color:#2D2D42">a</b><b style="color:#AB8785">a</b><b style="color:#665258">y</b><b style="color:#78797C">1</b><b style="color:#DDDFCE">2</b><b style="color:#FDFEE6">g</b><b style="color:#FFFFE9">1</b><b style="color:#FFFFE8">u</b><b style="color:#FFFEE6">a</b><b style="color:#FEFEE6">u1</b><b style="color:#FFFFE6">y</b><b style="color:#FFFFE7">12</b><b style="color:#FDFDE6">g</b><b style="color:#F3F3DC">0</b><b style="color:#FFFFE8">u</b><b style="color:#F3F3DD">g</b><b style="color:#FBFBE4">1</b><b style="color:#FFFFE8">a</b><b style="color:#FFFFE7">g</b><b style="color:#FFFFE6">a</b><b style="color:#FEFEE6">02</b><b style="color:#FFFFE6">a</b><b style="color:#FFFFE8">0</b><b style="color:#FFFFE9">y</b><b style="color:#FAFAE4">0</b><b style="color:#BCBFB0">a</b><b style="color:#58575C">a</b><b style="color:#8C7075">a</b><b style="color:#CC9E95">1</b><b style="color:#2B2939">2</b><b style="color:#26263A">u</b>
<b style="color:transparent">g</b><b style="color:#2A293E">a</b><b style="color:#373448">g</b><b style="color:#A6A8A2">a</b><b style="color:#FFFFED">1</b><b style="color:#FFFFEA">1</b><b style="color:#FFFFE7">y</b><b style="color:#FEFEE6">0gy2ay01</b><b style="color:#FFFFE7">y</b><b style="color:#FFFFE8">g</b><b style="color:#FEFEE6">y</b><b style="color:#FFFFE8">g</b><b style="color:#FFFFE7">1</b><b style="color:#FEFEE6">uu1gagg0</b><b style="color:#FFFFE7">1</b><b style="color:#FFFFED">0</b><b style="color:#F3F3E1">1</b><b style="color:#7D7F7A">g</b><b style="color:#3B3444">u</b><b style="color:#302F44">1</b><b style="color:#232335">g</b>
<b style="color:transparent">g</b><b style="color:#25253C">0</b><b style="color:#9D9E9B">u</b><b style="color:#FFFFEF">0</b><b style="color:#FFFFE7">2</b><b style="color:#FEFEE6">u21gu</b><b style="color:#FFFFE7">10</b><b style="color:#FEFEE6">00u12uu20gu</b><b style="color:#FFFFE7">0g</b><b style="color:#FEFEE6">2u0ga</b><b style="color:#FFFFE9">y</b><b style="color:#FEFEEC">y</b><b style="color:#7E7F79">u</b><b style="color:#24243B">y</b><b style="color:#252538">y</b>
<b style="color:transparent">a</b><b style="color:#515161">y</b><b style="color:#F9F9E2">0</b><b style="color:#FFFFE8">a</b><b style="color:#FEFEE6">2</b><b style="color:#FFFFE7">g</b><b style="color:#FFFFE9">1</b><b style="color:#FFFFE8">a1</b><b style="color:#FFFFEA">y</b><b style="color:#FFFFEB">2</b><b style="color:#F9F9E2">1</b><b style="color:#FEFEE6">0</b><b style="color:#FFFFE6">1</b><b style="color:#FEFEE6">a0g02u1</b><b style="color:#FFFFE6">g</b><b style="color:#FEFEE6">g</b><b style="color:#FBFBE4">1</b><b style="color:#FFFFEB">2</b><b style="color:#FFFFEA">2</b><b style="color:#FFFFE8">a0</b><b style="color:#FFFFE9">1</b><b style="color:#FFFFE8">0</b><b style="color:#FEFEE6">0</b><b style="color:#FFFFE9">2</b><b style="color:#ECECDD">a</b><b style="color:#414148">a</b><b style="color:#292941">y</b>
<b style="color:transparent">0</b><b style="color:#8C8C8F">2</b><b style="color:#FFFFF4">1</b><b style="color:#FFFFE7">ya</b><b style="color:#F4F4DE">g</b><b style="color:#E5E7D3">0</b><b style="color:#EFF0DB">u</b><b style="color:#F0F0DB">0</b><b style="color:#DDDDCD">a</b><b style="color:#8D8D8D">g</b><b style="color:#929290">a</b><b style="color:#FFFFE8">y</b><b style="color:#FFFFE7">1</b><b style="color:#FEFEE6">0yg</b><b style="color:#FFFFE9">u</b><b style="color:#FFFFE8">u</b><b style="color:#FEFEE6">g1</b><b style="color:#FFFFE7">1</b><b style="color:#FFFFE9">u</b><b style="color:#989897">u</b><b style="color:#8B8B8C">y</b><b style="color:#DDDDCC">0</b><b style="color:#F0F0DB">0</b><b style="color:#F0F1DB">y</b><b style="color:#E6E8D4">1</b><b style="color:#EEEEDA">a</b><b style="color:#FFFFE7">ay</b><b style="color:#FFFFF6">y</b><b style="color:#86867D">a</b><b style="color:#24243C">0</b>
<b style="color:transparent">u</b><b style="color:#72727A">a</b><b style="color:#B6B6AE">u</b><b style="color:#F2F2DD">a</b><b style="color:#FFFFE7">u</b><b style="color:#D2C9B9">u</b><b style="color:#857980">u</b><b style="color:#888287">2</b><b style="color:#878788">1</b><b style="color:#8C8C8C">0</b><b style="color:#B5B5AC">2</b><b style="color:#F6F6DF">a</b><b style="color:#FFFFE7">u</b><b style="color:#FEFEE6">u</b><b style="color:#FFFFE7">1</b><b style="color:#FFFFE8">u</b><b style="color:#FFFFE9">a</b><b style="color:#EAEAD7">2</b><b style="color:#F7F7E0">u</b><b style="color:#FFFFE9">u</b><b style="color:#FFFFE8">0</b><b style="color:#FFFFE7">02</b><b style="color:#F4F4DE">y</b><b style="color:#B2B2AB">y</b><b style="color:#8D8D8D">2</b><b style="color:#888889">u</b><b style="color:#847F84">u</b><b style="color:#7E727B">2</b><b style="color:#BDB8AC">0</b><b style="color:#FFFFE7">y</b><b style="color:#F6F6E0">y</b><b style="color:#B8B8AC">a</b><b style="color:#717173">1</b><b style="color:#27273E">g</b><b style="color:#232334">2</b>
<b style="color:transparent">y</b><b style="color:#575765">u</b><b style="color:#B6B6AD">u</b><b style="color:#EAEAD6">0</b><b style="color:#FFFFE9">0</b><b style="color:#F9DBD7">g</b><b style="color:#F49BBF">1</b><b style="color:#F4ADC6">0</b><b style="color:#FEFBE5">2</b><b style="color:#FFFFEC">g1</b><b style="color:#FFFFE7">2</b><b style="color:#FEFEE6">g</b><b style="color:#FFFFE7">y</b><b style="color:#F2F2DD">1</b><b style="color:#EDEDD9">y</b><b style="color:#DFDFCE">u</b><b style="color:#424253">g</b><b style="color:#8F8F90">1</b><b style="color:#F5F5DF">0</b><b style="color:#E9E9D6">0</b><b style="color:#FAFAE3">a</b><b style="color:#FFFFE7">y</b><b style="color:#FFFFE8">y</b><b style="color:#FFFFEC">g</b><b style="color:#FFFFEB">g</b><b style="color:#FEFEE7">u</b><b style="color:#F4B4C8">g</b><b style="color:#F399BE">a</b><b style="color:#FADAD7">a</b><b style="color:#FFFFE9">0</b><b style="color:#F0F0DA">1</b><b style="color:#B8B8AC">0</b><b style="color:#57575C">g</b><b style="color:#292940">u</b>
<b style="color:transparent">u</b><b style="color:#36364A">u</b><b style="color:#6D6D75">a</b><b style="color:#B5B5AD">1</b><b style="color:#FFFFEA">u</b><b style="color:#FDF6E3">a</b><b style="color:#F9D8D7">u</b><b style="color:#F9E1DA">0</b><b style="color:#FFFEE6">1</b><b style="color:#FFFFE7">y</b><b style="color:#FEFEE6">y12</b><b style="color:#FFFFEA">u</b><b style="color:#C9C9BC">0</b><b style="color:#7F7F82">2</b><b style="color:#7E7E82">y</b><b style="color:#979795">u</b><b style="color:#838385">0</b><b style="color:#808083">2</b><b style="color:#959593">0</b><b style="color:#F4F4DD">y</b><b style="color:#FFFFE8">g</b><b style="color:#FEFEE6">g0</b><b style="color:#FFFFE6">1</b><b style="color:#FFFFE7">1</b><b style="color:#FBE4DC">2</b><b style="color:#F9D8D7">a</b><b style="color:#FDF6E3">2</b><b style="color:#FFFFEC">2</b><b style="color:#C5C5B4">y</b><b style="color:#66666A">y</b><b style="color:#38384A">y</b><b style="color:#2B2B41">0</b><b style="color:#1B1B28">a</b>
<b style="color:transparent">1</b><b style="color:transparent">a</b><b style="color:#39394A">y</b><b style="color:#BDBBB2">1</b><b style="color:#FFFFE6">2</b><b style="color:#FFFFEC">0</b><b style="color:#FFFFEB">g</b><b style="color:#FFFFE9">a</b><b style="color:#FFFFE7">1</b><b style="color:#FFFFE6">y0</b><b style="color:#FEFEE6">100</b><b style="color:#FFFFE9">2</b><b style="color:#FEFEE8">0</b><b style="color:#FEFEE9">0</b><b style="color:#FFFFED">a</b><b style="color:#FFFFEB">0</b><b style="color:#FEFEE7">2</b><b style="color:#FFFFE9">g</b><b style="color:#FFFFE7">g</b><b style="color:#FEFEE6">21</b><b style="color:#FFFFE6">g</b><b style="color:#FFFFE7">g0</b><b style="color:#FFFFE9">0</b><b style="color:#FFFFEB">u</b><b style="color:#FFFFEC">a</b><b style="color:#FEFEE5">y</b><b style="color:#C0BEAF">y</b><b style="color:#403F4C">0</b><b style="color:#232438">2</b>
<b style="color:transparent">0g</b><b style="color:transparent">u</b><b style="color:#202030">1</b><b style="color:#69676F">a</b><b style="color:#B8B5AC">g</b><b style="color:#E8E6D2">g</b><b style="color:#FDFBE3">u</b><b style="color:#FFFFE9">u</b><b style="color:#FFFFEB">0g</b><b style="color:#FFFFEA">u</b><b style="color:#FFFFE9">01u</b><b style="color:#FFFFE8">20yg</b><b style="color:#FFFFE9">2a2</b><b style="color:#FFFFEA">ya</b><b style="color:#FFFFEB">uy</b><b style="color:#FFFFE9">0</b><b style="color:#FCFAE2">1</b><b style="color:#E8E5D1">2</b><b style="color:#BAB7AB">1</b><b style="color:#6D6A6F">a</b><b style="color:#2B2B3E">0</b>
<b style="color:transparent">2au0</b><b style="color:transparent">y</b><b style="color:#171724">1</b><b style="color:#3B3947">0</b><b style="color:#67646B">1</b><b style="color:#8E8A8A">0</b><b style="color:#ADA9A3">a</b><b style="color:#C5C1B5">1</b><b style="color:#D6D2C3">a</b><b style="color:#E1DECC">g</b><b style="color:#E9E6D2">g</b><b style="color:#EEEBD6">g</b><b style="color:#F1EFD9">1</b><b style="color:#F3F1DA">g</b><b style="color:#F3F1DB">2</b><b style="color:#F3F0DA">g</b><b style="color:#F1EED9">y</b><b style="color:#EDEBD6">1</b><b style="color:#E8E5D1">0</b><b style="color:#DFDCCA">1</b><b style="color:#D3CFC0">a</b><b style="color:#C3BFB4">g</b><b style="color:#ADA9A2">g</b><b style="color:#8E8B8A">2</b><b style="color:#69666D">2</b><b style="color:#413F4D">y</b><b style="color:#202030">2</b>
<b style="color:transparent">ygu00ay</b><b style="color:transparent">2</b><b style="color:#080811">u</b><b style="color:#12121E">y</b><b style="color:#1F1F2C">g</b><b style="color:#2D2C3A">1</b><b style="color:#3A3946">y</b><b style="color:#454350">g</b><b style="color:#4F4D59">1</b><b style="color:#56535F">g</b><b style="color:#5A5762">y</b><b style="color:#5C5964">2</b><b style="color:#5A5863">0</b><b style="color:#55535F">g</b><b style="color:#4E4C58">y</b><b style="color:#454350">a</b><b style="color:#393745">y</b><b style="color:#2C2B3A">a</b>
</pre>
</template>

<style lang="scss" scoped>
.ascii-cat {
  white-space: pre;
  font-family: inherit;
  letter-spacing: 0.1em;
  font-size: inherit;
}
</style>
